### PR TITLE
basic survey functionality

### PR DESCRIPTION
**Pull request by ben-jones**
This pull request adds surveys to the app.

@ggmartins, will you review?

### CODE REVIEW

**Comment by ggmartins** [comment]
New menu button: looks ok, I think you will replace the Configure option for something else right? because the content is replicated in Settings..

**Comment by ggmartins** [comment]
About option (menu button): nice to have a version/build number. We need to associate bugs with build numbers ( I can take care of that ).

**Comment by ggmartins** [comment]
Surveys: nexus 5 is showing text cut at "The following questionnaire investigates internet... (cut off here)"

**Comment by ggmartins** [comment]
DisplaySurvey: screen title is showing "DisplaySurvey", I think just "Survey" looks better (There's a "Hello word!" string for the webview android:text.  Also, the Settings option menu is empty..

**Comment by ben-jones** [comment]
@ggmartins, I updated the heading on DisplaySurvey to just "Survey" and I made the survey list items wrap content.

Also, my long term plan is to replace the configure tile with interference measurements.

**Pull request merged**
